# Makefile.Host
TOP = ../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

# Rules for installing EDM files:
CFG +=  CONFIG_EDL
# EDM Screens to install
#EDLS += Myfirst.edl

# Install images to be used by EDM (Gif and Png are supported)
#GIFS += Myfirst.gif
#PNGS += Myfirst.png




include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

